const express = require("express");
const router = express.Router();
const auth = require("../middleware/authMiddleware");
const { getProducts, getProductById, createProduct, updateProduct, deleteProduct } = require("../controllers/productController");
router.get("/",       auth, getProducts);
router.get("/:id",    auth, getProductById);
router.post("/",      auth, createProduct);
router.put("/:id",    auth, updateProduct);
router.delete("/:id", auth, deleteProduct);
module.exports = router;