const automationRoutes = require("./automation/routes/automationRoutes");
const express = require("express");
const helmet = require("helmet");
const cors = require("cors");
const authRoutes        = require("./routes/authRoutes");
const userRoutes        = require("./routes/userRoutes");
const productRoutes     = require("./routes/productRoutes");
const orderRoutes       = require("./routes/orderRoutes");
const customerRoutes    = require("./routes/customerRoutes");
const integrationRoutes = require("./routes/integrationRoutes");
const webhookRoutes     = require("./routes/webhookRoutes");
const reportRoutes      = require("./routes/reportRoutes");
const tenantRoutes      = require("./routes/tenantRoutes");
const planRoutes        = require("./routes/planRoutes");
const marketingRoutes   = require("./routes/marketingRoutes");
const eventRoutes       = require("./routes/eventRoutes");
const aiRoutes          = require("./routes/aiRoutes");
const onboardingRoutes  = require("./routes/onboardingRoutes");
const moduleRoutes = require("./routes/moduleRoutes");
const integrationCatalogRoutes = require("./routes/integrationCatalogRoutes");
const financeiroRoutes = require("./routes/financeiroRoutes");
const googleRoutes = require("./routes/googleRoutes");
const contabilidadeRoutes = require("./routes/contabilidadeRoutes");
const obrigacoesRoutes = require("./routes/obrigacoesRoutes");
const documentosRoutes = require("./routes/documentosRoutes");
const bancosRoutes = require("./routes/bancosRoutes");
const centrosCustoRoutes = require("./routes/centrosCustoRoutes");
const motorFinanceiroRoutes = require("./routes/motorFinanceiroRoutes");
const rentabilidadeRoutes = require("./routes/rentabilidadeRoutes");
const fluxoPreditivoRoutes = require("./routes/fluxoPreditivoRoutes");
const tesourariaRoutes = require("./routes/tesourariaRoutes");
const orcamentoRoutes = require("./routes/orcamentoRoutes");
const automacaoFinanceiraRoutes = require("./routes/automacaoFinanceiraRoutes");
const alertasRoutes = require("./routes/alertasRoutes");
const fechamentoRoutes = require("./routes/fechamentoRoutes");
const auditoriaRoutes = require("./routes/auditoriaRoutes");
const fiscalProfundoRoutes = require("./routes/fiscalProfundoRoutes");
const contractsRoutes = require("./routes/contractsRoutes");
const cardsRoutes = require("./routes/cardsRoutes");
const scenarioRoutes = require("./routes/scenarioRoutes");

const app = express();

app.use(helmet());
app.use(cors({ origin: "*", methods: ["GET","POST","PUT","DELETE"], allowedHeaders: ["Content-Type","Authorization"] }));
app.use(express.json());

app.use("/api/automations", automationRoutes);
app.use("/api/auth",         authRoutes);
app.use("/api/users",        userRoutes);
app.use("/api/products",     productRoutes);
app.use("/api/orders",       orderRoutes);
app.use("/api/customers",    customerRoutes);
app.use("/api/integrations", integrationRoutes);
app.use("/api/webhooks/automation", require("./automation/routes/automationWebhookRoutes"));
app.use("/api/webhooks",     webhookRoutes);
app.use("/api/reports",      reportRoutes);
app.use("/api/tenants",      tenantRoutes);
app.use("/api/plans",        planRoutes);
app.use("/api/marketing",    marketingRoutes);
app.use("/api/events",       eventRoutes);
app.use("/api/ai",           aiRoutes);
app.use("/api/onboarding",   onboardingRoutes);
app.use("/api/modules", moduleRoutes);
app.use("/api/integrations-catalog", integrationCatalogRoutes);
app.use("/api/financeiro", financeiroRoutes);
app.use("/api/google", googleRoutes);
app.use("/api/contabilidade", contabilidadeRoutes);
app.use("/api/obrigacoes", obrigacoesRoutes);
app.use("/api/documentos", documentosRoutes);
app.use("/api/bancos", bancosRoutes);
app.use("/api/centros-custo", centrosCustoRoutes);
app.use("/api/motor-financeiro", motorFinanceiroRoutes);
app.use("/api/rentabilidade", rentabilidadeRoutes);
app.use("/api/fluxo-preditivo", fluxoPreditivoRoutes);
app.use("/api/tesouraria", tesourariaRoutes);
app.use("/api/orcamento", orcamentoRoutes);
app.use("/api/automacao-financeira", automacaoFinanceiraRoutes);
app.use("/api/alertas", alertasRoutes);
app.use("/api/fechamento", fechamentoRoutes);
app.use("/api/auditoria", auditoriaRoutes);
app.use("/api/fiscal-profundo", fiscalProfundoRoutes);
app.use("/api/contratos", contractsRoutes);
app.use("/api/cartoes", cardsRoutes);
app.use("/api/cenarios", scenarioRoutes);
app.use("/api/marketing/leads", require("./routes/marketingLeadsRoutes"));
app.use("/api/marketing/segments", require("./routes/marketingSegmentsRoutes"));
app.use("/api/marketing/campaigns", require("./routes/marketingCampaignsRoutes"));
app.use("/api/marketing/scoring", require("./routes/marketingScoringRoutes"));
app.use("/api/marketing/attribution", require("./routes/marketingAttributionRoutes"));
app.use("/api/marketing/journeys", require("./routes/marketingJourneysRoutes"));
app.use("/api/marketing/dashboard", require("./routes/marketingDashboardRoutes"));
app.use("/api/marketing/forms", require("./routes/marketingFormsRoutes"));
app.use("/api/marketing/landing-pages", require("./routes/marketingLandingPagesRoutes"));
app.use("/api/marketing/ab-tests", require("./routes/marketingAbTestsRoutes"));
app.use("/api/stock", require("./routes/stockRoutes"));
app.use("/api/crm", require("./routes/crmRoutes"));
app.use("/api/crm/dashboard", require("./routes/crmDashboardRoutes"));
app.use("/api/bi", require("./routes/biRoutes"));

module.exports = app;
